#' @title Parameter estimation of (semi)parametric integer autoregressive models
#'
#' @description
#' Performs a semiparametric estimation of the autoregressive parameters and the innovation distribution for the integer-valued autoregressive model of order \code{p} (INAR(\code{p})) for \code{p in {1,2}}, the estimation is conducted by maximizing the conditional likelihood of the model.
#'
#' @param x [\code{integer}]\cr
#' vector of integer values corresponding to the data used for estimating the parameters via maximum likelihood.
#' @param p [\code{integer(1)}]\cr
#' Lag of the INAR(p) where \code{p in \{1,2\}}
#'
#' @return parameters [\code{numeric(p+max(x)+1)}]\cr
#'
#' Return the estimated parameters \code{(alpha_1, ..., alpha_p, pmf0, pmf1, ...)},
#' where \code{(alpha_1, ..., alpha_p)} are the estimated autoregressive coefficients
#' and \code{(pmf0, pmf1, ...)} are the estimated entries of the probability mass function of the innovation distribution, here \code{pmfi} denotes the entry of the integer \code{i} in \code{x}.
#'
#' @examples
#' ## Parameter estimation for p = 1 and x as a vector of values.
#' spinar(c(2, 3, 1, 1, 1, 1, 1, 1, 3), 1)
#' ### returns (alpha_1, pmf0, pmf1, pmf2, pmf3)
#' ## Parameter estimation for p = 2 and data generated by rpois.
#' spinar(rpois(100, 0.8), 2)
#' ### returns (alpha_1, alpha_2, pmf0, ...)
#' @export

spinar <- function(x, p) {
  # constraints for input
  checkmate::assert_integerish(p, lower = 1, min.len = 1, max.len = 1, upper = 2)
  checkmate::assert_integerish(x, min.len = p+1)
  xmax <- max(x)
  if(p==1){
    theta <- c(max(acf(x, plot = FALSE)$acf[p+1], 1e-5), rep(1 / (xmax + 1), xmax))
  }
  if(p==2){
    eacf1 <- acf(x, plot=FALSE)$acf[p+1]
    eacf2 <- acf(x, plot=FALSE)$acf[p+2]
    ealpha2 <- (eacf2-eacf1^2)/(1-eacf1^2)
    ealpha1 <- (1-ealpha2)*eacf1
    theta <- c(max(ealpha1, 1e-5), max(ealpha2, 1e-5), rep(1 / (xmax + 1), xmax))}
  if (max(x) == min(x)){
    parameters <- c(1, rep(0, p-1), 1, rep(0, xmax))
  }
  else {
    est <-suppressWarnings(constrOptim(
      theta = theta,
      f = llspinar[[p]],
      grad = NULL,
      ui = .constrmat(p, xmax),
      ci = .constrvec(p, xmax),
      dat = x
    ))
    parameters <- est$par
    parameters <- c(parameters[seq_len(p)],
                    1-sum(parameters[-seq_len(p)]),
                    parameters[-seq_len(p)])
  }
  return(parameters)
}

